name: hashids
description: A Clojure library to generate short unique ids from integers, for brevity and obfuscation of database IDs.
version: 1.0.1

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
