name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install

      - name: Install Clojure CLI
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run Babashka Tests
        run: bb test

      - name: Run Clojure JVM Tests
        run: clojure -M:test:clj

      - name: Run ClojureScript Tests
        run: clojure -M:test:cljs

      - name: Install dotnet
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Install Clojure CLR
        run: |
          dotnet tool install --global Clojure.Main
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha9

      - name: Run Clojure CLR Tests
        run: cljr -X:test:cljr

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Run ClojureDart Tests
        run: clojure -M:test:cljd test
